FROM gcc:latest

# Set the working director
WORKDIR /app

# Copy the server code into the container
COPY http_server.cpp /app/http_server.cpp

# Compile the server code
RUN g++ -o http_server http_server.cpp

# Expose the server port
EXPOSE 8081

# Command to run the HTTP server
CMD ["./http_server"]

