name: Multi-Arch Docker

on:
  push:
    branches:
      - branchHTTPserverMulti

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and configure project
        run: |
          autoreconf -i
          ./configure
          make

      - name: Log in to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin

      - name: Build and Push Multi-Arch Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: zorenkod/httpserver:latest
          platforms: linux/amd64,linux/arm64

         


