name: AutoTest

on:
  push:
    branches:
      - branchAutoTest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build DebianPackage
        run: |
          ./configure
          make check
         


