name: DebianPackage

on:
  push:
    branches:
      - branchAutoPackage

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build DebianPackage
        run: |
          ./configure --prefix=/
          make install DESTDIR=$(pwd)
          dpkg-deb --build deb
         


